/*
 * driver/gpio.h - pico-sdk compatibility shim.
 *
 * Two jobs:
 *
 *  1. Provide GPIO_NUM_0..47 and GPIO_NUM_NC. The board profile generated by
 *     scripts/generate_board_profile.py emits pin masks as
 *     (1ULL << GPIO_NUM_<n>), so these must exist for the generated header to
 *     compile. Keeping them means the generator stays reusable verbatim
 *     instead of needing an RP2350-specific output mode.
 *  2. Map the handful of ESP-IDF GPIO calls used by the shared sources onto
 *     pico-sdk's hardware_gpio.
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RP2350B exposes GPIO0-GPIO47. */
typedef int gpio_num_t;

#define GPIO_NUM_NC (-1)
#define GPIO_NUM_0   0
#define GPIO_NUM_1   1
#define GPIO_NUM_2   2
#define GPIO_NUM_3   3
#define GPIO_NUM_4   4
#define GPIO_NUM_5   5
#define GPIO_NUM_6   6
#define GPIO_NUM_7   7
#define GPIO_NUM_8   8
#define GPIO_NUM_9   9
#define GPIO_NUM_10 10
#define GPIO_NUM_11 11
#define GPIO_NUM_12 12
#define GPIO_NUM_13 13
#define GPIO_NUM_14 14
#define GPIO_NUM_15 15
#define GPIO_NUM_16 16
#define GPIO_NUM_17 17
#define GPIO_NUM_18 18
#define GPIO_NUM_19 19
#define GPIO_NUM_20 20
#define GPIO_NUM_21 21
#define GPIO_NUM_22 22
#define GPIO_NUM_23 23
#define GPIO_NUM_24 24
#define GPIO_NUM_25 25
#define GPIO_NUM_26 26
#define GPIO_NUM_27 27
#define GPIO_NUM_28 28
#define GPIO_NUM_29 29
#define GPIO_NUM_30 30
#define GPIO_NUM_31 31
#define GPIO_NUM_32 32
#define GPIO_NUM_33 33
#define GPIO_NUM_34 34
#define GPIO_NUM_35 35
#define GPIO_NUM_36 36
#define GPIO_NUM_37 37
#define GPIO_NUM_38 38
#define GPIO_NUM_39 39
#define GPIO_NUM_40 40
#define GPIO_NUM_41 41
#define GPIO_NUM_42 42
#define GPIO_NUM_43 43
#define GPIO_NUM_44 44
#define GPIO_NUM_45 45
#define GPIO_NUM_46 46
#define GPIO_NUM_47 47
#define GPIO_NUM_MAX 48

typedef enum {
    GPIO_MODE_DISABLE = 0,
    GPIO_MODE_INPUT,
    GPIO_MODE_OUTPUT,
    GPIO_MODE_OUTPUT_OD,
    GPIO_MODE_INPUT_OUTPUT_OD,
    GPIO_MODE_INPUT_OUTPUT,
} gpio_mode_t;

typedef enum { GPIO_PULLUP_DISABLE = 0, GPIO_PULLUP_ENABLE } gpio_pullup_t;
typedef enum { GPIO_PULLDOWN_DISABLE = 0, GPIO_PULLDOWN_ENABLE } gpio_pulldown_t;

typedef enum {
    GPIO_INTR_DISABLE = 0,
    GPIO_INTR_POSEDGE,
    GPIO_INTR_NEGEDGE,
    GPIO_INTR_ANYEDGE,
    GPIO_INTR_LOW_LEVEL,
    GPIO_INTR_HIGH_LEVEL,
} gpio_int_type_t;

typedef enum {
    GPIO_FLOATING = 0,
    GPIO_PULLUP_ONLY,
    GPIO_PULLDOWN_ONLY,
    GPIO_PULLUP_PULLDOWN,
} gpio_pull_mode_t;

typedef struct {
    uint64_t pin_bit_mask;
    gpio_mode_t mode;
    gpio_pullup_t pull_up_en;
    gpio_pulldown_t pull_down_en;
    gpio_int_type_t intr_type;
} gpio_config_t;

esp_err_t gpio_config(const gpio_config_t *config);
esp_err_t gpio_reset_pin(gpio_num_t pin);
esp_err_t gpio_set_direction(gpio_num_t pin, gpio_mode_t mode);
esp_err_t gpio_set_pull_mode(gpio_num_t pin, gpio_pull_mode_t pull);
esp_err_t gpio_set_level(gpio_num_t pin, uint32_t level);
int gpio_get_level(gpio_num_t pin);
esp_err_t gpio_pullup_en(gpio_num_t pin);
esp_err_t gpio_pullup_dis(gpio_num_t pin);
esp_err_t gpio_pulldown_en(gpio_num_t pin);
esp_err_t gpio_pulldown_dis(gpio_num_t pin);

/* ESP-IDF's shared GPIO ISR service. Nothing in the picocalc-core flavour
 * registers a GPIO edge interrupt (see solar_os_compat_pico_gpio.c), so these
 * report "unavailable" rather than silently accepting a handler that will
 * never fire - callers here already treat a non-ESP_OK result as "no
 * interrupt source" and fall back accordingly. */
static inline esp_err_t gpio_install_isr_service(int flags)
{ (void)flags; return ESP_ERR_NOT_SUPPORTED; }

static inline esp_err_t gpio_isr_handler_add(gpio_num_t pin,
                                             void (*handler)(void *),
                                             void *arg)
{ (void)pin; (void)handler; (void)arg; return ESP_ERR_NOT_SUPPORTED; }

/* RP2350B exposes GPIO0-47 as ordinary bidirectional digital pins (no
 * input-only pins the way some ESP32 variants have), so "valid" and "valid
 * output" collapse to the same range check. */
#define GPIO_IS_VALID_GPIO(pin) ((pin) >= 0 && (pin) < GPIO_NUM_MAX)
#define GPIO_IS_VALID_OUTPUT_GPIO(pin) GPIO_IS_VALID_GPIO(pin)

#ifdef __cplusplus
}
#endif
